// <auto-generated />
using System;
using BE__Small_Shop_Management_System.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE__Small_Shop_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024043602_FixRolePermissionSeed")]
    partial class FixRolePermissionSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.InventoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChanged")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryHistories");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.PasswordPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("RequireDigit")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireLowercase")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireNonAlphanumeric")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireUppercase")
                        .HasColumnType("bit");

                    b.Property<int>("RequiredLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PasswordPolicies");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7226),
                            Description = "Xem danh sách người dùng",
                            Module = "Người dùng",
                            Name = "Users.View"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7268),
                            Description = "Tạo mới người dùng",
                            Module = "Người dùng",
                            Name = "Users.Create"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7275),
                            Description = "Cập nhật thông tin người dùng",
                            Module = "Người dùng",
                            Name = "Users.Update"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7281),
                            Description = "Xóa người dùng",
                            Module = "Người dùng",
                            Name = "Users.Delete"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7286),
                            Description = "Khóa tài khoản người dùng",
                            Module = "Người dùng",
                            Name = "Users.Lock"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7292),
                            Description = "Mở khóa tài khoản người dùng",
                            Module = "Người dùng",
                            Name = "Users.Unlock"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7323),
                            Description = "Users ResetPassword",
                            Module = "Người dùng",
                            Name = "Users.ResetPassword"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7349),
                            Description = "Xem danh sách vai trò",
                            Module = "Vai trò",
                            Name = "Roles.View"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7355),
                            Description = "Tạo mới vai trò",
                            Module = "Vai trò",
                            Name = "Roles.Create"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7361),
                            Description = "Cập nhật vai trò",
                            Module = "Vai trò",
                            Name = "Roles.Update"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7367),
                            Description = "Xóa vai trò",
                            Module = "Vai trò",
                            Name = "Roles.Delete"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7376),
                            Description = "Xem danh sách quyền",
                            Module = "Quyền",
                            Name = "Permissions.View"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7382),
                            Description = "Permissions Create",
                            Module = "Quyền",
                            Name = "Permissions.Create"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7387),
                            Description = "Permissions Update",
                            Module = "Quyền",
                            Name = "Permissions.Update"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7396),
                            Description = "Xóa quyền",
                            Module = "Quyền",
                            Name = "Permissions.Delete"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7420),
                            Description = "Xem danh sách sản phẩm",
                            Module = "Sản phẩm",
                            Name = "Products.View"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7427),
                            Description = "Thêm mới sản phẩm",
                            Module = "Sản phẩm",
                            Name = "Products.Create"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7432),
                            Description = "Cập nhật sản phẩm",
                            Module = "Sản phẩm",
                            Name = "Products.Update"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7438),
                            Description = "Xóa sản phẩm",
                            Module = "Sản phẩm",
                            Name = "Products.Delete"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7443),
                            Description = "Products Import",
                            Module = "Sản phẩm",
                            Name = "Products.Import"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7451),
                            Description = "Products Export",
                            Module = "Sản phẩm",
                            Name = "Products.Export"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7462),
                            Description = "Xem danh sách đơn hàng",
                            Module = "Đơn hàng",
                            Name = "Orders.View"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7467),
                            Description = "Tạo mới đơn hàng",
                            Module = "Đơn hàng",
                            Name = "Orders.Create"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7472),
                            Description = "Cập nhật đơn hàng",
                            Module = "Đơn hàng",
                            Name = "Orders.Update"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7476),
                            Description = "Xóa đơn hàng",
                            Module = "Đơn hàng",
                            Name = "Orders.Delete"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7506),
                            Description = "Xử lý đơn hàng",
                            Module = "Đơn hàng",
                            Name = "Orders.Process"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7516),
                            Description = "Orders Cancel",
                            Module = "Đơn hàng",
                            Name = "Orders.Cancel"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7527),
                            Description = "Xem kho hàng",
                            Module = "Kho",
                            Name = "Inventory.View"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7532),
                            Description = "Nhập hàng vào kho",
                            Module = "Kho",
                            Name = "Inventory.Import"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7549),
                            Description = "Inventory Export",
                            Module = "Kho",
                            Name = "Inventory.Export"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7557),
                            Description = "Inventory Update",
                            Module = "Kho",
                            Name = "Inventory.Update"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7564),
                            Description = "Reports View",
                            Module = "Báo cáo",
                            Name = "Reports.View"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7570),
                            Description = "Reports Generate",
                            Module = "Báo cáo",
                            Name = "Reports.Generate"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7576),
                            Description = "Reports Export",
                            Module = "Báo cáo",
                            Name = "Reports.Export"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7587),
                            Description = "Xem danh mục sản phẩm",
                            Module = "Danh mục",
                            Name = "Categories.View"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7593),
                            Description = "Tạo mới danh mục",
                            Module = "Danh mục",
                            Name = "Categories.Create"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7597),
                            Description = "Cập nhật danh mục",
                            Module = "Danh mục",
                            Name = "Categories.Update"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7604),
                            Description = "Xóa danh mục",
                            Module = "Danh mục",
                            Name = "Categories.Delete"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7611),
                            Description = "Xem nhật ký hệ thống",
                            Module = "Nhật ký hệ thống",
                            Name = "SystemLogs.View"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7616),
                            Description = "Xóa nhật ký hệ thống",
                            Module = "Nhật ký hệ thống",
                            Name = "SystemLogs.Delete"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7622),
                            Description = "Xem trang tổng quan",
                            Module = "Tổng quan",
                            Name = "Dashboard.View"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7626),
                            Description = "Dashboard Analyze",
                            Module = "Tổng quan",
                            Name = "Dashboard.Analyze"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7681),
                            Description = "Xem chính sách mật khẩu",
                            Module = "Chính sách mật khẩu",
                            Name = "PasswordPolicy.View"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7690),
                            Description = "Cập nhật chính sách mật khẩu",
                            Module = "Chính sách mật khẩu",
                            Name = "PasswordPolicy.Update"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7699),
                            Description = "Xem giỏ hàng",
                            Module = "Giỏ hàng",
                            Name = "Cart.View"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7704),
                            Description = "Thêm sản phẩm vào giỏ hàng",
                            Module = "Giỏ hàng",
                            Name = "Cart.Add"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7709),
                            Description = "Cập nhật giỏ hàng",
                            Module = "Giỏ hàng",
                            Name = "Cart.Update"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7714),
                            Description = "Xóa sản phẩm khỏi giỏ hàng",
                            Module = "Giỏ hàng",
                            Name = "Cart.Delete"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7722),
                            Description = "Xem danh sách yêu thích",
                            Module = "Yêu thích",
                            Name = "Favorites.View"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7726),
                            Description = "Thêm sản phẩm yêu thích",
                            Module = "Yêu thích",
                            Name = "Favorites.Add"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7731),
                            Description = "Xóa sản phẩm yêu thích",
                            Module = "Yêu thích",
                            Name = "Favorites.Delete"
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7738),
                            Description = "Xem chi tiết sản phẩm trong đơn hàng",
                            Module = "Chi tiết đơn hàng",
                            Name = "OrderItems.View"
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7744),
                            Description = "Xem lịch sử nhập xuất kho",
                            Module = "Lịch sử kho",
                            Name = "InventoryHistory.View"
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7749),
                            Description = "Nhập hàng vào kho",
                            Module = "Lịch sử kho",
                            Name = "InventoryHistory.Import"
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2025, 10, 24, 4, 36, 2, 283, DateTimeKind.Utc).AddTicks(7755),
                            Description = "InventoryHistory Export",
                            Module = "Lịch sử kho",
                            Name = "InventoryHistory.Export"
                        });
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Seller"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 39
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 40
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 46
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 47
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 48
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 49
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 50
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 52
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 54
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 55
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 54
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 55
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 46
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 47
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 48
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 49
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 50
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 51
                        });
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 11, 36, 2, 283, DateTimeKind.Local).AddTicks(8101),
                            Email = "admin@system.com",
                            FullName = "Trần Văn Khởi",
                            IsActive = true,
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            PasswordHash = "$2a$11$26OigAKWgJw/jcdfeeZV7OeQoBSKk0dwA8fuWWAnUU8H/AsVGzYd6",
                            PhoneNumber = "0356995423",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.CartItem", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BE__Small_Shop_Management_System.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Favorite", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE__Small_Shop_Management_System.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.InventoryHistory", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Product", "Product")
                        .WithMany("InventoryHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Order", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.OrderItem", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BE__Small_Shop_Management_System.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Payment", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("BE__Small_Shop_Management_System.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Product", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.ProductImage", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.RefreshToken", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.RolePermission", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BE__Small_Shop_Management_System.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.SystemLog", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.UserPermission", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BE__Small_Shop_Management_System.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.UserRole", b =>
                {
                    b.HasOne("BE__Small_Shop_Management_System.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE__Small_Shop_Management_System.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("InventoryHistories");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BE__Small_Shop_Management_System.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
